### ISSUE TITLE
填写了uid貌似没出来数据----

### ISSUE THREAD

**Issue by ruanbaojun1105** [a252937166/toutiaocrawler#1]
无奈

**Comment by a252937166** [comment]
问题已经解决，重新pull一下最新代码就可以了，简单说一下我的解决思路吧：
1.启动项目，在`"/toutiao/add"`方法中debug，发现`http.doGet()`的返回值中`data`是空的。这样问题就定位到获取任务列表这里了。

2.在`String url = "https://www.toutiao.com/pgc/ma/?....`debug，copy生成好的url，粘贴到浏览器打开，发现浏览器中获取的数据是正常的。
同时发现控制台打印出了`[route: {s}->https://www.toutiao.com:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]`。
443错误，显然是因为某种原因，头条识别出来我是爬虫，把我的访问屏蔽了。应该是近期他们的反爬手段升级了，之前是没有的。

3.浏览器访问和java访问，最大的区别肯定是浏览器参数了。我的`httpClient`之前都是用的默认设置。

4.先设置一大堆参数，比如`accept:*/*`,`connection:Keep-Alive`，最后定位到是因为`user-agent`，因为如果你不设置的话，默认是`Apache-HttpClient/4.5.3`，很容易就被发现了，我改为了`Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1;SV1)`问题就解决了。

防反爬的基本手段就是设置代理，大量访问之后，还可能出现封杀IP的情况，这时候就需要设置proxy，修改你的ip来实现反爬。

**Comment by ruanbaojun1105** [comment]
@a252937166 谢谢 现在数据能得到，视频也能自动生成，发现youtube上传并没有那么简单，现在卡住了.....

**Comment by ruanbaojun1105** [comment]
![image](https://user-images.githubusercontent.com/7459297/39734273-347d2624-52a9-11e8-8ce2-ddd3e6aeb2e5.png)为啥我出来的数据是这样啊？而且我再设置Agent也是这样

**Comment by ruanbaojun1105** [comment]
妈耶好麻烦---我先去搞自动上传

**Comment by ruanbaojun1105** [comment]
401763159有空交流下大佬

**Comment by a252937166** [comment]
我原本的例子是海台网，它的内容页是静态页面，所以我用的`Jsoup`解析，获取内容、标题、作者等。
我试了一下你的id，发现内容页是动态页面，也就是说内容不是直接写到html中的，是通过js产生的，不能用海台网的解析方式，解析相对复杂一点，我重新写了一套，你拉取分支上的代码看看就懂了。

到底加不加header，需要在浏览器中打开对应网址看一下，header设置为跟浏览器打开时一样就行了。

**Comment by ruanbaojun1105** [comment]
自动上传ok,现在我先用海台网的数据吧

**Comment by ruanbaojun1105** [comment]
现在我没有用web方式爬数据了 ，我改用android去爬数据，不过你写的有借鉴意义，谢谢大佬
